pcfg_file_name: 'pcfg_bigger.txt'
saved_model_name: 'bigger_model'

train_size: 10000
val_size: 2000
test_size: 2000
batch_size: 32

max_len: 50
n_layer: 2
n_head: 4
n_embd: 256
dropout: 0.1

max_iter: 1200
eval_interval: 300
lr: 6e-4

num_sen_to_generate: 5
generate_max_len: 15
return_probs: True